version: '3.9'

services:
  todo :
    build: .
    ports:
      - '8000:8000'
    container_name: todo
    command :
     - python manage.py runserver 0.0.0.0:8000


    volumes:
      - .:/app

    depends_on:
      - redis




  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      - '143:143'
    volumes:
      # This is where smtp4dev stores the database..
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__Urls=http://*:80

      - ServerOptions__HostName=smtp4dev

  redis:
    container_name: todo-redis
    image: redis
    restart: always
    ports:
    - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  worker :
    build: .
    command: celery -A core beat -l info

    depends_on:
      - redis
      - todo
    volumes:
      - ./:/app


volumes:
  smtp4dev-data: