# Generated by Django 5.1.1 on 2024-09-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_remove_todo_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="is_delete",
            field=models.BooleanField(default=False),
        ),
    ]
