name: Todo App Test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker Todo Compose 
      run: docker compose up -d

    - name: Run Flake 
      run: docker compose exec todo sh -c 'flake8 .'

    # - name: Run PyTest
    #   run: docker compose exec todo sh -c 'pytest .'

  Deploy:
    if : ${{ contains(join(needs.*.result, ','), 'success') }}
    name: Deploy on server
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses : actions/checkout@v4
      - name : Connect and run commands
        uses : webfactory/ssh-agent@v0.9.0
        with :
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ${{ secrets.VENV }}
            git pull drf master 
            echo 'done!!!'