name: Todo App Test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker Todo Compose 
      run: docker compose up -d

    - name: Run Flake8
      run: docker compose exec todo sh -c 'flake8 .'

    # - name: Run PyTest
    #   run: docker compose exec todo sh -c 'pytest .'

  Deploy:
    if : ${{ contains(join(needs.*.result, ','), 'success') }}
    name: Deploy on server
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses : actions/checkout@v4
      - name : Connect and run commands
        uses : SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          script: |
            - source ${{secrets.VENV}}
            - gh repo clone maryus1991/simpleDjangoProject
            
